# Generated by Django 4.0.1 on 2022-01-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todolist', models.CharField(max_length=400, verbose_name='Цель')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=30, verbose_name='Статус')),
                ('description', models.TextField(default='Подробное описание отсутствует', max_length=2000, null=True, verbose_name='Описание')),
                ('deadline', models.DateField(blank=True, default=None, null=True, verbose_name='Дата когда задача выполнена')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'db_table': 'to_do_list',
            },
        ),
    ]
